glory_menu:
    path: /admin/menu
    defaults: { _controller: GloryMenuBundle:Admin:list }

glory_menu_create:
    path: /admin/menu/create
    defaults: { _controller: GloryMenuBundle:Admin:create }

glory_menu_show:
    path: /admin/menu/{id}
    defaults: { _controller: GloryMenuBundle:Admin:show }

glory_menu_add:
    path: /admin/menu/{id}/add
    defaults: { _controller: GloryMenuBundle:Admin:add }

glory_menu_edit:
    path: /admin/menu/{id}/edit
    defaults: { _controller: GloryMenuBundle:Admin:edit }

glory_menu_delete:
    path: /admin/menu/{id}/delete
    defaults: { _controller: GloryMenuBundle:Admin:delete }
