services:
    glory_menu.menu_manager:
        class: Glory\Bundle\MenuBundle\Model\MenuManager
        arguments: [@service_container]
    glory_menu.menu_provider:
        class: Glory\Bundle\MenuBundle\Menu\Provider\MenuProvider
        arguments: [@glory_menu.menu_manager]
        tags:
          - { name: knp_menu.provider }
    glory_menu.twig.extension:
        class: Glory\Bundle\MenuBundle\Twig\Extension\MenuExtension
        arguments: [@knp_menu.helper, @glory_menu.menu_manager]
        public: false
        tags:
            - { name: twig.extension }
          
    glory_menu.util.menu_tree:
        class: Glory\Bundle\MenuBundle\Util\MenuTree

    glory_menu.form.menu:
        class: Glory\Bundle\MenuBundle\Form\Type\MenuFormType
        arguments: [@glory_menu.menu_manager]
        tags:
            - { name: form.type, alias: glory_menu_form }
    glory_menu.form.menu_type:
        class: Glory\Bundle\MenuBundle\Form\Type\MenuType
        arguments: [@glory_menu.menu_manager]
        tags:
            - { name: form.type, alias: glory_menu }
    glory_menu.form.menu_attrs_type:
        class: Glory\Bundle\MenuBundle\Form\Type\AttributesType
        tags:
            - { name: form.type, alias: glory_menu_attributes }
    glory_menu.form.menu_link_type:
        class: Glory\Bundle\MenuBundle\Form\Type\LinkType
        tags:
            - { name: form.type, alias: glory_menu_link }